---
title: "Graphs and Tables and Figures Oh My"
author: "Brianna Saylor"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gtsummary) # making tables
library(gt) # making tables 
library(flextable)
library(broom)
library(dplyr) # data manipulation
library(ggplot2) # making graphs
library(tidyverse)  # importing, tidying, plotting data
library(knitr)      # making tables in markdown
library(leaflet)    # making maps in markdown 
library(hexbin)
library(tidyr) # data manipulation 
obs <- read.csv("data/grassland-bird-species-obs_09July25.csv")
veg <- read.csv("data/grassland-bird-veg_09July25.csv")
point.count <- read.csv("data/grassland-bird-point-count_18Sept25.csv")
```

```{r clean observation data, echo=FALSE, include=FALSE}
# check data for issues 
summary(obs)
obs$point_id <- as.factor(obs$point_id) # point id factor
obs$species <- as.factor(obs$species) # species factor 
obs$flyover <- as.factor(obs$flyover) # flyover factor 
unique(obs$point_id)
summary(obs)
```

```{r clean up vegetation data, echo=FALSE, include=FALSE}
summary(veg)
veg$point_id <- as.factor(veg$point_id) # point id factor 
veg$site_type <- as.factor(veg$site_type) # site type factor 
unique(veg$point_id)
summary(veg)
```

```{r clean up point count data, echo=FALSE, include=FALSE}
summary(point.count)
point.count$point_id <- as.factor(point.count$point_id) # point id as factor
point.count <- point.count %>% 
  mutate(date = dmy(date)) # change date format to year-month-day
summary(point.count)
```

```{r filtering observation data, include=FALSE}
obs.nofly.100 <- filter(obs, flyover == "No") # remove observations that are flyovers
obs.nofly.100 <- filter(obs.nofly.100, dist <= 100) # remove observations over 100 m from point
# selecting all grassland species 
obs.grassland <- filter(obs.nofly.100, species == "HESP" | species == "GRSP" | species == "EAME" |
                             species == "NOBO" | species == "PRAW" | species == "YBCH" | 
                          species == "INBU" | species == "FISP" | species == "RWBL" | 
                          species == "COYE" | species == "DICK" | species == "BLGR" | species == "EAKI")
```

```{r summarize species obs by point id, include=FALSE}
obs.grassland.sum <- obs.grassland %>% 
  group_by(point_id, species) %>% 
  summarise(total = sum(number), .groups = "drop") %>% 
  tidyr::pivot_wider(names_from = species, values_from = total, values_fill = 0)
```

```{r removing columns from point count data, include=FALSE} 
point.count <- point.count %>% 
  dplyr::select(-observer, -start_time, -lat, -lon, -zone)
point.count$date <- yday(point.count$date) # change date to julian date
```

```{r preparing the veg data, include=FALSE}
veg <- veg %>% 
  dplyr::select(-date)
veg <- veg %>%
  mutate(site_id = sub("^[0-9]+-", "", point_id)) # add a column for site id based off point id 
veg$site_id <- as.factor(veg$site_id) # site id as factor
unique(veg$site_id)
```

```{r combing into one df, include=FALSE}
combined.grassland <- veg %>% 
  full_join(obs.grassland.sum, by = "point_id") %>% 
  full_join(point.count, by = "point_id")
combined.grassland <- combined.grassland %>% 
  mutate(across(c(COYE, INBU, FISP, PRAW, RWBL, YBCH, BLGR, EAKI, NOBO, DICK, EAME, GRSP, HESP), ~replace_na(.x, 0))) # replace NA values with 0
sum(is.na(combined.grassland)) # check for NAs
```

```{r species richness  and evenness, include=FALSE}
# add shannons index column 
library(vegan) # calculates the shannon and simpson index
# add species richness column
combined.grassland <- combined.grassland %>% 
  mutate(richness = rowSums(across(c(COYE, INBU, FISP, PRAW, RWBL, YBCH, BLGR, EAKI, NOBO, DICK, EAME, GRSP, HESP)) > 0))
# add shannons index column  
combined.grassland <- combined.grassland  %>% 
  rowwise() %>% 
  mutate(
    shannon = diversity(across(c(COYE, INBU, FISP, PRAW, RWBL, YBCH, BLGR, EAKI, NOBO, DICK, EAME, GRSP, HESP)), index = "shannon")) %>%
  ungroup()
combined.grassland <- combined.grassland %>% 
  mutate(across(c("shannon"), round, 2))
```

```{r cleaning combined data, include=FALSE}
combined.grassland$point_id <- as.factor(combined.grassland$point_id)
combined.grassland$site_type <- as.factor(combined.grassland$site_type)
combined.grassland$site_id <- as.factor(combined.grassland$site_id)
```

```{r converting percent cover to percentage, include=FALSE}
combined.grassland <- combined.grassland %>%
  mutate(across(c(pc_woody, pc_grass), ~ (.x / 20) * 100))
```


## **Site Types**

Add descriptions and pictures of site types. 

### **Vegetation Characteristics**

```{r table anova site vegetation differences, message=FALSE, warning=FALSE}
table_site_veg <- combined.grassland %>%
  select(site_type, veg_ht_avg, vd_vo, litter_avg, pc_woody, pc_grass) %>% #retain variables used in summaries
  tbl_summary(by = site_type,
              missing = "no", # remove missing values (NAs). "ifany" will include a missing values row in table.
              digits = all_continuous() ~ 1, #number of displayed digits for continuous variables
              label = list(veg_ht_avg ~ "Vegetation Height (cm)", #change column labels in table
                           vd_vo ~ "Visual Observation (cm)",
                           litter_avg ~ "Litter Depth (cm)",
                           pc_woody ~ "Percent Woody Cover",
                           pc_grass ~ "Percent Grass Cover"),
              statistic = list(all_continuous() ~ "{mean} ({sd})", #can use any character for parentheses
                               all_categorical() ~ "{n}")) %>% #count obs. for categorical variables
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 2)) %>% #number of digits displayed for p-values
  modify_caption("Table 1. Vegetation Characteristics of the Different Site Types") %>%
  modify_header(update = all_stat_cols() ~ "**{level}**") #headers to only contain site names
```

```{r format table anova site vegetation differences, fig.align='center'}
table_site_veg %>% 
  modify_header(label = '') %>%
  as_gt() %>% 
  opt_stylize(style = 6, color = 'green') %>%
  opt_align_table_header(align = "left") %>%
  tab_options(heading.align = "left")
```

### **Site Level Characteristics**

```{r table anova site characteristic difference, message=FALSE}
table_site_site <- combined.grassland %>%
  select(site_type, site_ha, site_pa_ratio) %>% #retain variables used in summaries
  tbl_summary(by = site_type,
              missing = "no", # remove missing values (NAs). "ifany" will include a missing values row in table.
              digits = all_continuous() ~ 1, #number of displayed digits for continuous variables
              label = list(site_ha ~ "Site Size (ha)", #change column labels in table
                           site_pa_ratio ~ "Site Perimeter-Area Ratio"),
              statistic = list(all_continuous() ~ "{mean} ({sd})", #can use any character for parentheses
                               all_categorical() ~ "{n}")) %>% #count obs. for categorical variables
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 2)) %>% #number of digits displayed for p-values
  modify_caption("Table 2. Site Level Characteristics of the Different Site Types") %>%
  modify_header(update = all_stat_cols() ~ "**{level}**") #headers to only contain site names
```

```{r format table anova site characteristic difference, fig.align='center'}
table_site_site %>% 
  modify_header(label = '') %>%
  as_gt() %>% 
  opt_stylize(style = 6, color = 'green') %>%
  opt_align_table_header(align = "left") %>%
  tab_options(heading.align = "left")
```


### **Bird Diversity**

```{r table anova bird diversity, message=FALSE}
table_bird_diversity <- combined.grassland %>%
  select(site_type, richness, HESP, GRSP, EAME, NOBO, YBCH, PRAW) %>% #retain variables used in summaries
  tbl_summary(by = site_type,
              missing = "no", # remove missing values (NAs). "ifany" will include a missing values row in table.
              digits = all_continuous() ~ 1, #number of displayed digits for continuous variables
              label = list(richness ~ "Species Richness (n)", #change column labels in table
                           HESP ~ "Henslow's Sparrow (n)", 
                           GRSP ~ "Grasshopper Sparrow (n)", 
                           EAME ~ "Eastern Meadowlark (n)",
                           NOBO ~ "Northern Bobwhite (n)", 
                           YBCH ~ "Yellow-breasted Chat (n)", 
                           PRAW ~ "Prairie Warbler (n)"),
              statistic = list(all_continuous() ~ "{mean} ({sd})", #can use any character for parentheses
                               all_categorical() ~ "{n}")) %>% #count obs. for categorical variables
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 2)) %>% #number of digits displayed for p-values
  modify_caption("Table 3. Bird Diversity at Different Site Types") %>%
  modify_header(update = all_stat_cols() ~ "**{level}**") #headers to only contain site names
```

```{r will this code work}
table_bird_diversity <- combined.grassland %>%
  select(site_type, richness) %>% #retain variables used in summaries
  tbl_summary(by = site_type,
              missing = "no", # remove missing values (NAs). "ifany" will include a missing values row in table.
              digits = all_continuous() ~ 1, #number of displayed digits for continuous variables
              label = list(richness ~ "Species Richness (n)" #change column labels in table
                ),
              statistic = list(all_continuous() ~ "{mean} ({sd})", #can use any character for parentheses
                               all_categorical() ~ "{n}")) %>% #count obs. for categorical variables
  add_p(test = list(all_continuous() ~ "t.test"),
    pvalue_fun = ~style_pvalue(.x, digits = 2)) %>% #number of digits displayed for p-values
  modify_caption("Table 3. Bird Diversity at Different Site Types") %>%
  modify_header(update = all_stat_cols() ~ "**{level}**") #headers to only contain site names
```

```{r}
table_bird_diversity <- combined.grassland %>%
  select(site_type, NOBO) %>% #retain variables used in summaries
  tbl_summary(by = site_type,
              missing = "no", # remove missing values (NAs). "ifany" will include a missing values row in table.
              digits = all_continuous() ~ 1, #number of displayed digits for continuous variables
              label = list(NOBO ~ "Northern Bobwhite (n)" #change column labels in table
                ),
              statistic = list(all_continuous() ~ "{mean} ({sd})", #can use any character for parentheses
                               all_categorical() ~ "{n}")) %>% #count obs. for categorical variables
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 2)) %>% #number of digits displayed for p-values
  modify_caption("Table 3. Bird Diversity at Different Site Types") %>%
  modify_header(update = all_stat_cols() ~ "**{level}**") #headers to only contain site names
```

```{r}
table_bird_diversity %>% 
  modify_header(label = '') %>%
  as_gt() %>% 
  opt_stylize(style = 6, color = 'blue') %>%
  opt_align_table_header(align = "left") %>%
  tab_options(heading.align = "left")
```

